### ISSUE TITLE
Anime not playing or downloading

### ISSUE THREAD

**Issue by goodryan4** [daose/KSAnime-kissanime#5]
I noticed this when I was trying to start the season "all out!!". It just would not play or even show a pop up of the choice of resolution for the video. Is this a kissanime problem or is it simply a problem with the app for my phone?

**Comment by daose** [comment]
unfortunately openload/beta server isn't supported, I am looking into alternate sources though.

**Comment by goodryan4** [comment]
thanks for the quick reply

**Comment by daose** [comment]
@goodryan4 openload is now supported :)

**Comment by goodryan4** [comment]
Thanks for the update.
