### ISSUE TITLE
Samsung galaxy s7 android 7.0 app crashes

### ISSUE THREAD

**Issue by goodryan4** [daose/KSAnime-kissanime#6]
Whenever my device does a device maintenance check it detects an error. I am not sure what the error is but I have noticed freezing in the app at times. The app is beautiful and works properly so I am not sure why it freezes.

**Comment by daose** [comment]
Hey thanks for letting me know :)

I know the app has a few small memory leaks (working on it!) here and there, but nothing major enough to cause a crash/freeze that I've experienced.

I'm not sure where to start looking to solve this though, so if I could ask you to either

1) When it crashes, please report the error, this lets me see the log output from your phone

2) Screenshot the maintenance check? I'm not sure if it would reveal more information, but I've never done a "device maintenance check" before so I'm not too sure what it is.

3) Is the crash reproducible? Do you find yourself doing some sort of action that usually causes the crash?

**Comment by goodryan4** [comment]
Here is a screenshot of the device maintainance. It does not really say
much but I think it has to do with the app not being compatible with the
doze mode on the Samsung galaxy s7.

**Comment by goodryan4** [comment]
I believe that I fixed the random crashing on my device. I disable force gpu rendering on 2d applications in developer options and have not had a crash since. The other error for device maintainance still occurs though. It says that "24 errors have occurred in 1 week". It does not even tell me what the errors are. I am using a non rooted phone. Is there any way to see the log output?

**Comment by daose** [comment]
So was it crashing because gpu rendering was on? or because gpu rendering was off? I'm guessing this might have something to do with the blurred gradient background image.

Do you know if those errors existed before v3.0 (when news and notifications were added)?

(also I couldn't see the screenshot, I guess github issues doesn't include attachments from your e-mail?)

**Comment by goodryan4** [comment]
Here is a google drive link. I hope this works.
  Screenshot_20170405-220418.png
<https://drive.google.com/a/ocdsb.ca/file/d/0B3_HD7Apdk9kVWxVMnpUaDAzSlU/view?usp=drivesdk>
I believe that since the "force gpu rendering" was on, the background
images had problems rendering and it crashed the app.

**Comment by goodryan4** [comment]
Here is the initial screen before I clicked the "fix button" in the device
maintainance.
  Original.png
<https://drive.google.com/a/ocdsb.ca/file/d/0B3_HD7Apdk9kLWVGUTJDS1c4R2M/view?usp=drivesdk>

**Comment by daose** [comment]
There are some things I can try, but since I can't pinpoint the problem I won't know if it solves it. Please bear with it for now and look forward to the next app update!

**Comment by goodryan4** [comment]
I have found a way to crash the ksanime app and it is very simple. I simply put my Samsung galaxy s7 into power savings mode. Then I open the app and close the app. My screen then freezes and the ksanime app crashes.

**Comment by goodryan4** [comment]
https://drive.google.com/a/ocdsb.ca/file/d/0B3_HD7Apdk9kcUJzVnpyQncycGs/view?usp=drivesdk

https://drive.google.com/a/ocdsb.ca/file/d/0B3_HD7Apdk9kVEdLTHRRYWl3Y3c/view?usp=drivesdk

**Comment by goodryan4** [comment]
The power savings mode decreases the screen resolution of my screen from fhd to be and the enables a speed limiter on my cpu.

**Comment by goodryan4** [comment]
Hd* not be

**Comment by daose** [comment]
I tried power saving mode with samsung s4 and wasn't able to reproduce the crash.

When the app crashes, there should be an option with the crash pop up that asks if you want to __report__ the crash. If you see it, could you please report it?

I'm guessing this might be because of outdated third party libraries that I'm using, but I can't tell which one, seeing the crash log would be very helpful for me!

**Comment by goodryan4** [comment]
Ok

**Comment by goodryan4** [comment]
Since the last update I have not had an error.
