### ISSUE TITLE
Picture problems at random.

### ISSUE THREAD

**Issue by goodryan4** [daose/KSAnime-kissanime#7]
https://drive.google.com/a/ocdsb.ca/file/d/0B3_HD7Apdk9kdTZ4V2FyeFg2TnM/view?usp=drivesdk

Black picture. I am not sure if it is simply my app's cache.

**Comment by goodryan4** [comment]
Sorry my google drive did not want to share the image. Here is the pic. https://drive.google.com/file/d/0B9xiKAb-D-UXTjFXa0pBTVZnVjg/view?usp=drivesdk

**Comment by daose** [comment]
Thanks for the screenshot, my best guess is that the long title has something to do with it, will look into it!

**Comment by daose** [comment]
should be fixed with the next release
